package model

//*****************************************************************************
//
//     _         _           ____                           _           _
//    / \  _   _| |_ ___    / ___| ___ _ __   ___ _ __ __ _| |_ ___  __| |
//   / _ \| | | | __/ _ \  | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` |
//  / ___ \ |_| | || (_) | | |_| |  __/ | | |  __/ | | (_| | ||  __/ (_| |
// /_/   \_\__,_|\__\___/   \____|\___|_| |_|\___|_|  \__,_|\__\___|\__,_|
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// Implementation(s) of TEnvironmentHooks
// ----------------------------------------------------

//TEnvironmentHooksOnEnvironmentHooksHolder is the struct containing the EnvironmentHooks in order to implement TEnvironmentHooks
type TEnvironmentHooksOnEnvironmentHooksHolder struct {
	h EnvironmentHooks
}

//CreateTEnvironmentHooksForEnvironmentHooks returns an holder of EnvironmentHooks implementing TEnvironmentHooks
func CreateTEnvironmentHooksForEnvironmentHooks(o EnvironmentHooks) TEnvironmentHooksOnEnvironmentHooksHolder {
	return TEnvironmentHooksOnEnvironmentHooksHolder{
		h: o,
	}
}

//HasInit returns true if the hooks has tasks while before creating
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasInit() bool {
	return r.h.Init.HasTasks()
}

//Init returns the initialization tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Init() THook {
	return CreateTHookForHook(r.h.Init)
}

//HasCreate returns true if the hooks has tasks while creating
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasCreate() bool {
	return r.h.Create.HasTasks()
}

//Create returns the creating tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Create() THook {
	return CreateTHookForHook(r.h.Create)
}

//HasInstall returns true if the hooks has tasks while installing
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasInstall() bool {
	return r.h.Install.HasTasks()
}

//Install returns the installing tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Install() THook {
	return CreateTHookForHook(r.h.Install)
}

//HasDeploy returns true if the hooks has tasks while deploying
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasDeploy() bool {
	return r.h.Deploy.HasTasks()
}

//Deploy returns the deploying tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Deploy() THook {
	return CreateTHookForHook(r.h.Deploy)
}

//HasDelete returns true if the hooks has tasks while deleting
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasDelete() bool {
	return r.h.Delete.HasTasks()
}

//Delete returns the deletion tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Delete() THook {
	return CreateTHookForHook(r.h.Delete)
}
