package model

//*****************************************************************************
//
//     _         _           ____                           _           _
//    / \  _   _| |_ ___    / ___| ___ _ __   ___ _ __ __ _| |_ ___  __| |
//   / _ \| | | | __/ _ \  | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` |
//  / ___ \ |_| | || (_) | | |_| |  __/ | | |  __/ | | (_| | ||  __/ (_| |
// /_/   \_\__,_|\__\___/   \____|\___|_| |_|\___|_|  \__,_|\__\___|\__,_|
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// Implementation(s) of TTaskRef
// ----------------------------------------------------

//TTaskRefOnTaskRefHolder is the struct containing the TaskRef in order to implement TTaskRef
type TTaskRefOnTaskRefHolder struct {
	h TaskRef
}

//CreateTTaskRefForTaskRef returns an holder of TaskRef implementing TTaskRef
func CreateTTaskRefForTaskRef(o TaskRef) TTaskRefOnTaskRefHolder {
	return TTaskRefOnTaskRefHolder{
		h: o,
	}
}

//Task returns the task corresponding to the ref
func (r TTaskRefOnTaskRefHolder) Task() (TTask, error) {
	v, err := r.h.Resolve()
	return CreateTTaskForTask(v), err
}
