package model

//*****************************************************************************
//
//     _         _           ____                           _           _
//    / \  _   _| |_ ___    / ___| ___ _ __   ___ _ __ __ _| |_ ___  __| |
//   / _ \| | | | __/ _ \  | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` |
//  / ___ \ |_| | || (_) | | |_| |  __/ | | |  __/ | | (_| | ||  __/ (_| |
// /_/   \_\__,_|\__\___/   \____|\___|_| |_|\___|_|  \__,_|\__\___|\__,_|
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// Implementation(s) of TStackRef
// ----------------------------------------------------

//TStackRefOnStackRefHolder is the struct containing the StackRef in order to implement TStackRef
type TStackRefOnStackRefHolder struct {
	h StackRef
}

//CreateTStackRefForStackRef returns an holder of StackRef implementing TStackRef
func CreateTStackRefForStackRef(o StackRef) TStackRefOnStackRefHolder {
	return TStackRefOnStackRefHolder{
		h: o,
	}
}

//Stack returns the stack corresponding to the ref
func (r TStackRefOnStackRefHolder) Stack() (TStack, error) {
	v, err := r.h.Resolve()
	return CreateTStackForStack(v), err
}
