package model

//*****************************************************************************
//
//     _         _           ____                           _           _
//    / \  _   _| |_ ___    / ___| ___ _ __   ___ _ __ __ _| |_ ___  __| |
//   / _ \| | | | __/ _ \  | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` |
//  / ___ \ |_| | || (_) | | |_| |  __/ | | |  __/ | | (_| | ||  __/ (_| |
// /_/   \_\__,_|\__\___/   \____|\___|_| |_|\___|_|  \__,_|\__\___|\__,_|
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// Implementation(s) of TProxy
// ----------------------------------------------------

//TProxyOnProxyHolder is the struct containing the Proxy in order to implement TProxy
type TProxyOnProxyHolder struct {
	h Proxy
}

//CreateTProxyForProxy returns an holder of Proxy implementing TProxy
func CreateTProxyForProxy(o Proxy) TProxyOnProxyHolder {
	return TProxyOnProxyHolder{
		h: o,
	}
}

//HTTP returns the proxy http definition
func (r TProxyOnProxyHolder) HTTP() string {
	return r.h.Http
}

//HTTPS returns the proxy https definition
func (r TProxyOnProxyHolder) HTTPS() string {
	return r.h.Https
}

//NoProxy returns the no proxy definition
func (r TProxyOnProxyHolder) NoProxy() string {
	return r.h.NoProxy
}
