package model

//*****************************************************************************
//
//     _         _           ____                           _           _
//    / \  _   _| |_ ___    / ___| ___ _ __   ___ _ __ __ _| |_ ___  __| |
//   / _ \| | | | __/ _ \  | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` |
//  / ___ \ |_| | || (_) | | |_| |  __/ | | |  __/ | | (_| | ||  __/ (_| |
// /_/   \_\__,_|\__\___/   \____|\___|_| |_|\___|_|  \__,_|\__\___|\__,_|
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// Implementation(s) of TCopy
// ----------------------------------------------------

//TCopyOnCopyHolder is the struct containing the Copy in order to implement TCopy
type TCopyOnCopyHolder struct {
	h Copy
}

//CreateTCopyForCopy returns an holder of Copy implementing TCopy
func CreateTCopyForCopy(o Copy) TCopyOnCopyHolder {
	return TCopyOnCopyHolder{
		h: o,
	}
}

//HasLabels returns true if the copy has defined labels
func (r TCopyOnCopyHolder) HasLabels() bool {
	return len(r.h.Labels) > 0
}

//Labels returns the copy labels
func (r TCopyOnCopyHolder) Labels() map[string]string {
	return r.h.Labels
}

//HasSources returns true if the copy has defined sources
func (r TCopyOnCopyHolder) HasSources() bool {
	return len(r.h.Sources.Content) > 0
}

//Sources returns the copy sources
func (r TCopyOnCopyHolder) Sources() []string {
	return r.h.Sources.Content
}
