package model

//*****************************************************************************
//
//     _         _           ____                           _           _
//    / \  _   _| |_ ___    / ___| ___ _ __   ___ _ __ __ _| |_ ___  __| |
//   / _ \| | | | __/ _ \  | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` |
//  / ___ \ |_| | || (_) | | |_| |  __/ | | |  __/ | | (_| | ||  __/ (_| |
// /_/   \_\__,_|\__\___/   \____|\___|_| |_|\___|_|  \__,_|\__\___|\__,_|
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// Implementation(s) of TProvider
// ----------------------------------------------------

//TProviderOnProviderHolder is the struct containing the Provider in order to implement TProvider
type TProviderOnProviderHolder struct {
	h Provider
}

//CreateTProviderForProvider returns an holder of Provider implementing TProvider
func CreateTProviderForProvider(o Provider) TProviderOnProviderHolder {
	return TProviderOnProviderHolder{
		h: o,
	}
}

//Name returns the name of the provider
func (r TProviderOnProviderHolder) Name() string {
	return r.h.Name
}

//Parameters returns the provider parameters
func (r TProviderOnProviderHolder) Parameters() map[string]interface{} {
	return r.h.Parameters
}

//EnvVars returns the provider environment variables
func (r TProviderOnProviderHolder) EnvVars() map[string]string {
	return r.h.EnvVars
}

//Proxy returns the proxy definition applied to the provider
func (r TProviderOnProviderHolder) Proxy() TProxy {
	return CreateTProxyForProxy(r.h.Proxy)
}

//Component returns the provider component
func (r TProviderOnProviderHolder) Component() (TComponent, error) {
	v, err := r.h.Component()
	return CreateTComponentForComponent(v), err
}
