package model

//*****************************************************************************
//
//     _         _           ____                           _           _
//    / \  _   _| |_ ___    / ___| ___ _ __   ___ _ __ __ _| |_ ___  __| |
//   / _ \| | | | __/ _ \  | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` |
//  / ___ \ |_| | || (_) | | |_| |  __/ | | |  __/ | | (_| | ||  __/ (_| |
// /_/   \_\__,_|\__\___/   \____|\___|_| |_|\___|_|  \__,_|\__\___|\__,_|
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// Implementation(s) of TEnvironmentHooks
// ----------------------------------------------------

//TEnvironmentHooksOnEnvironmentHooksHolder is the struct containing the EnvironmentHooks in order to implement TEnvironmentHooks
type TEnvironmentHooksOnEnvironmentHooksHolder struct {
	h EnvironmentHooks
}

//CreateTEnvironmentHooksForEnvironmentHooks returns an holder of EnvironmentHooks implementing TEnvironmentHooks
func CreateTEnvironmentHooksForEnvironmentHooks(o EnvironmentHooks) TEnvironmentHooksOnEnvironmentHooksHolder {
	return TEnvironmentHooksOnEnvironmentHooksHolder{
		h: o,
	}
}

//HasProvision returns true if the hooks has tasks while provisioning
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasProvision() bool {
	return r.h.Provision.HasTasks()
}

//Provision returns the provisioning tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Provision() THook {
	return CreateTHookForHook(r.h.Provision)
}

//HasDestroy returns true if the hooks has tasks while destroying
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasDestroy() bool {
	return r.h.Destroy.HasTasks()
}

//Destroy returns the destroying tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Destroy() THook {
	return CreateTHookForHook(r.h.Destroy)
}

//HasDeploy returns true if the hooks has tasks while deploying
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasDeploy() bool {
	return r.h.Deploy.HasTasks()
}

//Deploy returns the deploying tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Deploy() THook {
	return CreateTHookForHook(r.h.Deploy)
}

//HasUndeploy returns true if the hooks has tasks while undeploying
func (r TEnvironmentHooksOnEnvironmentHooksHolder) HasUndeploy() bool {
	return r.h.Undeploy.HasTasks()
}

//Undeploy returns the undeploying tasks
func (r TEnvironmentHooksOnEnvironmentHooksHolder) Undeploy() THook {
	return CreateTHookForHook(r.h.Undeploy)
}
